### ISSUE TITLE
Refactoring codice

### ISSUE THREAD

**Issue by simonerocchi** [Mind-Informatica-srl/registro#2]
Separare il codice contenuto rispettivamente in registro.go e registro_test.go nei file (i nomi dei file dovranno essere tutti minuscoli):
- listamovimenti.go e listamovimenti_test.go
- registro.go che conterrà la struct del registro
- AddMovimentoToRegistro.go AddMovimentoToRegistro_test.go
- ModifyMovimentoToRegistro.go ModifyMovimentoToRegistro_test.go
- EliminareMovimentoToRegistro EliminareMovimentoToRegistro_test.go
- CreaCsvFile.go CreaCsvFile_test.go
- riordinaRegistro.go riordinaRegistro_test.go
- trovaIndice.go trovaIndice_test.go

**Comment by fabiodev30** [comment]
riprendere da less lista movimenti, non devo controllare posizione elemneti ma se un elemento è più piccolo di un altro
